
package com.example.soapexamclient.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.soapexam.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sellProduct", targetNamespace = "http://service.soapexam.example.com/", className = "com.example.soapexamclient.service.SellProduct")
    @ResponseWrapper(localName = "sellProductResponse", targetNamespace = "http://service.soapexam.example.com/", className = "com.example.soapexamclient.service.SellProductResponse")
    @Action(input = "http://service.soapexam.example.com/ProductService/sellProductRequest", output = "http://service.soapexam.example.com/ProductService/sellProductResponse")
    public void sellProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns java.util.List<com.example.soapexamclient.service.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAll", targetNamespace = "http://service.soapexam.example.com/", className = "com.example.soapexamclient.service.ListAll")
    @ResponseWrapper(localName = "listAllResponse", targetNamespace = "http://service.soapexam.example.com/", className = "com.example.soapexamclient.service.ListAllResponse")
    @Action(input = "http://service.soapexam.example.com/ProductService/listAllRequest", output = "http://service.soapexam.example.com/ProductService/listAllResponse")
    public List<Product> listAll();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://service.soapexam.example.com/", className = "com.example.soapexamclient.service.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://service.soapexam.example.com/", className = "com.example.soapexamclient.service.AddProductResponse")
    @Action(input = "http://service.soapexam.example.com/ProductService/addProductRequest", output = "http://service.soapexam.example.com/ProductService/addProductResponse")
    public void addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

}
